// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function InstallTheme(arg1:string,arg2:string):Promise<main.CustomTheme>;

export function OpenThemeStore():Promise<void>;

export function SearchThemes(arg1:string):Promise<Array<main.OpenVSXExtension>>;

export function SetMinimiseToTrayOnClose(arg1:boolean):Promise<void>;

export function SetRestoreShortcutEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
