// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateExprProgram(arg1, arg2) {
  return window['go']['main']['App']['EvaluateExprProgram'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallTheme(arg1, arg2) {
  return window['go']['main']['App']['InstallTheme'](arg1, arg2);
}

export function OpenThemeStore() {
  return window['go']['main']['App']['OpenThemeStore']();
}

export function SearchThemes(arg1) {
  return window['go']['main']['App']['SearchThemes'](arg1);
}

export function SetMinimiseToTrayOnClose(arg1) {
  return window['go']['main']['App']['SetMinimiseToTrayOnClose'](arg1);
}

export function SetRestoreShortcutEnabled(arg1) {
  return window['go']['main']['App']['SetRestoreShortcutEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
