// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureRandomState() {
  return window['go']['main']['App']['CaptureRandomState']();
}

export function ClearAIAPIKey(arg1) {
  return window['go']['main']['App']['ClearAIAPIKey'](arg1);
}

export function EvaluateExprProgram(arg1, arg2) {
  return window['go']['main']['App']['EvaluateExprProgram'](arg1, arg2);
}

export function ExportWorksheetPlaintextToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportWorksheetPlaintextToFile'](arg1, arg2);
}

export function GetAIKeyStatusForSettings(arg1) {
  return window['go']['main']['App']['GetAIKeyStatusForSettings'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetDefaultWorksheetDirectory() {
  return window['go']['main']['App']['GetDefaultWorksheetDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallTheme(arg1, arg2) {
  return window['go']['main']['App']['InstallTheme'](arg1, arg2);
}

export function IsRunningAsMSIX() {
  return window['go']['main']['App']['IsRunningAsMSIX']();
}

export function LoadWorksheetFromFile(arg1) {
  return window['go']['main']['App']['LoadWorksheetFromFile'](arg1);
}

export function OpenThemeStore() {
  return window['go']['main']['App']['OpenThemeStore']();
}

export function RestoreRandomState(arg1) {
  return window['go']['main']['App']['RestoreRandomState'](arg1);
}

export function RunAIQuery(arg1) {
  return window['go']['main']['App']['RunAIQuery'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveWorksheetToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveWorksheetToFile'](arg1, arg2);
}

export function SearchThemes(arg1) {
  return window['go']['main']['App']['SearchThemes'](arg1);
}

export function SelectWorksheetEncryptedSavePath(arg1) {
  return window['go']['main']['App']['SelectWorksheetEncryptedSavePath'](arg1);
}

export function SelectWorksheetLoadPath() {
  return window['go']['main']['App']['SelectWorksheetLoadPath']();
}

export function SelectWorksheetPlaintextExportPath(arg1) {
  return window['go']['main']['App']['SelectWorksheetPlaintextExportPath'](arg1);
}

export function SetAIAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAIAPIKey'](arg1, arg2);
}

export function SetMinimiseToTrayOnClose(arg1) {
  return window['go']['main']['App']['SetMinimiseToTrayOnClose'](arg1);
}

export function SetRestoreShortcutEnabled(arg1) {
  return window['go']['main']['App']['SetRestoreShortcutEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
