// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAIAPIKey(arg1:main.AISettings):Promise<main.AIKeyStatus>;

export function EvaluateExprProgram(arg1:string,arg2:Record<string, any>):Promise<main.ExprEvalResponse>;

export function GetAIKeyStatusForSettings(arg1:main.AISettings):Promise<main.AIKeyStatus>;

export function GetAISettings():Promise<main.AISettingsResponse>;

export function IsRunningAsMSIX():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function InstallTheme(arg1:string,arg2:string):Promise<main.CustomTheme>;

export function OpenThemeStore():Promise<void>;

export function RunAIQuery(arg1:main.AIRunRequest):Promise<main.AIRunResponse>;

export function SaveAISettings(arg1:main.AISettings):Promise<main.AISettingsResponse>;

export function SearchThemes(arg1:string):Promise<Array<main.OpenVSXExtension>>;

export function SetAIAPIKey(arg1:string,arg2:main.AISettings):Promise<main.AIKeyStatus>;

export function SetMinimiseToTrayOnClose(arg1:boolean):Promise<void>;

export function SetRestoreShortcutEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
